### ISSUE TITLE
v35 tag should use v35 mysql release

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/cf-mysql-deployment#3]
The current deployment is broken since it still uses v34 which assumes `properties.nats`:
https://github.com/cloudfoundry/cf-mysql-deployment/blob/v35/cf-mysql-deployment.yml#L127-L131

**Comment by menicosia** [comment]
Hi @rkoster,

Yep, you're right. And thanks for validating that people really are paying attention. I thought we could sneak out the release and get to [#144828263](https://www.pivotaltracker.com/story/show/144828263) immediately after. I'll make sure to put these updates immediately below the release banner from now on.

---

Marco Nicosia
Product Manager

**Comment by rkoster** [comment]
No problem, just know that concourse is watching :)

**Comment by menicosia** [comment]
Hi @rkoster,

There's a [v35](https://github.com/cloudfoundry/cf-mysql-deployment/tree/v35) tag now. It took us a few days to get it right, so if you've previously fetch'd it, it may help to `git tag -d v35 && git fetch --tags && git co v35`.

I'll close this now, but please feel free to open this issue, or open a new issue, if you find another goof. Thanks for the feedback!

---

Marco Nicosia
Product Manager

**Comment by rkoster** [comment]
@menicosia thanks!
