### ISSUE TITLE
cf-mysql-deployment missing proxy-static-ips operations file

### ISSUE THREAD

**Issue by menicosia** [cloudfoundry/cf-mysql-deployment#5]
**Context** In #136469529, we took out the need for static IPs. In #136539935, we added a `add-proxy-static-ips.yml` operations file, but it went in `cf-mysql-release/examples/bosh2.0/overrides` and was never carried over to `cf-mysql-deployment`.

Now, I am hearing reports that people are re-deploying without any requirement for static IPs, which causes the proxies to lose their static IP. This means that they cannot sit behind most load balancers.

**When** I follow updated `cf-mysql-deployment` instructions that cover the need to preserve and/or deploy using static IPs (for instance, when sitting behind a manually configured load balancer),
**Then** I am able to deploy `cf-mysql-release` using `cf-mysql-deployment`, and deploying with `add-broker.yml` without having the error:

```
14:08:07 | Updating instance broker: broker/2c9e0b19-7c04-47c6-9561-1128a9a69994 (0) (canary) (00:10:19)
            L Error: 'broker/0 (2c9e0b19-7c04-47c6-9561-1128a9a69994)' is not running after update. Review logs for failed jobs: cf-mysql-broker, quota-enforcer
```

**Comment by utricularian** [comment]
We've provided documentation for this https://github.com/cloudfoundry/cf-mysql-deployment/commit/378d3c48005dd138f4acf10f8bfabe270b96cda2 and will not create an opsfile.

We also have another story referencing static IPs when migrating from spiff to bosh2.0 style manifests.
