### ISSUE TITLE
cf_mysql_mysql_galera_healthcheck_db_password not found

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-mysql-deployment#8]
Hi team:
  When i deploy cf-mysql-deployment.it throw
![default](https://user-images.githubusercontent.com/21106445/36893843-8007d04c-1e44-11e8-9bf2-72770dee391b.png)
  I using -l env-repo/deployment-vars.yml. it not found `cf_mysql_mysql_galera_healthcheck_db_password` value` in deployment-vars.yml

**Comment by APShirley** [comment]
Hi @geekyzk 
The error you are seeing means bosh is trying to generate/retrieve a password from a config-server like [credhub](https://github.com/pivotal-cf/credhub-release).
 If you do not have pre-generated credentials the try using the `--vars-store /path/to/file` option to store generated credentials stored locally in a file instead, or deploy a config-server to store your credentials in. You can also add your own password value for `cf_mysql_mysql_galera_healthcheck_db_password` manually in your `deployment-vars.yml` file.
Thanks,
Nitya & Al
